// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LeadForm: typeof import('./app/components/LeadForm.vue')['default']
    TheFooter: typeof import('./app/components/TheFooter.vue')['default']
    TheHeader: typeof import('./app/components/TheHeader.vue')['default']
    UAlert: typeof import('@nuxt/ui')['UAlert']
    UAutocomplete: typeof import('@nuxt/ui')['UAutocomplete']
    UAvatar: typeof import('@nuxt/ui')['UAvatar']
    UBadge: typeof import('@nuxt/ui')['UBadge']
    UButton: typeof import('@nuxt/ui')['UButton']
    UButtonGroup: typeof import('@nuxt/ui')['UButtonGroup']
    UCard: typeof import('@nuxt/ui')['UCard']
    UCheckbox: typeof import('@nuxt/ui')['UCheckbox']
    UChip: typeof import('@nuxt/ui')['UChip']
    UCommandPalette: typeof import('@nuxt/ui')['UCommandPalette']
    UContainer: typeof import('@nuxt/ui')['UContainer']
    UDropdown: typeof import('@nuxt/ui')['UDropdown']
    UForm: typeof import('@nuxt/ui')['UForm']
    UFormGroup: typeof import('@nuxt/ui')['UFormGroup']
    UIcon: typeof import('@nuxt/ui')['UIcon']
    UInput: typeof import('@nuxt/ui')['UInput']
    UKbd: typeof import('@nuxt/ui')['UKbd']
    ULink: typeof import('@nuxt/ui')['ULink']
    UModal: typeof import('@nuxt/ui')['UModal']
    UNotification: typeof import('@nuxt/ui')['UNotification']
    UPagination: typeof import('@nuxt/ui')['UPagination']
    UPopover: typeof import('@nuxt/ui')['UPopover']
    UProgress: typeof import('@nuxt/ui')['UProgress']
    URadio: typeof import('@nuxt/ui')['URadio']
    URange: typeof import('@nuxt/ui')['URange']
    USelect: typeof import('@nuxt/ui')['USelect']
    USkeleton: typeof import('@nuxt/ui')['USkeleton']
    USlider: typeof import('@nuxt/ui')['USlider']
    UTable: typeof import('@nuxt/ui')['UTable']
    UTabs: typeof import('@nuxt/ui')['UTabs']
    UTextarea: typeof import('@nuxt/ui')['UTextarea']
    UToggle: typeof import('@nuxt/ui')['UToggle']
    UTooltip: typeof import('@nuxt/ui')['UTooltip']
  }
}
